### ISSUE TITLE
Current look and feel

### ISSUE THREAD

**Issue by froi** [department-of-veterans-affairs/github-handbook#1]
Here are some screenshots of the current look and feel:

**Main screen:**

![VA GitHub Handbook](https://user-images.githubusercontent.com/1918027/56818382-86ff7000-6815-11e9-8f96-8d2a4c8c350f.png)

**2FA flow:**

![VA GitHub Handbook - Setting up 2FA](https://user-images.githubusercontent.com/1918027/56818387-88c93380-6815-11e9-9461-b9df28785b82.png)

**Join VA flow:**

![VA GitHub Handbook - Joining the VA](https://user-images.githubusercontent.com/1918027/56818400-8d8de780-6815-11e9-9a53-71f41190e01b.png)

Please add any thoughts or questions here.

CC: @elstudio @nataliebradley @agantcurtis

**Comment by selkins13** [comment]
closing as no responses received.  Will be working on new updates in the coming weeks.
